services:
  redis:
    container_name: fhir-r4-mapper-redis
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  redisinsight:
    container_name: fhir-r4-mapper-redisinsight
    image: redis/redisinsight:latest
    ports:
      - '5540:5540'
    depends_on:
      - redis

volumes:
  redis-data:
